name: Build FFmpeg for Raspberry Pi 4B

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install full toolchain
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          gcc-11-aarch64-linux-gnu g++-11-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          libc6-dev-arm64-cross \
          pkg-config-aarch64-linux-gnu \
          qemu-user-static \
          crossbuild-essential-arm64

    - name: Setup environment
      run: |
        # 创建必要的sysroot链接
        sudo mkdir -p /usr/aarch64-linux-gnu
        [ -d "/usr/aarch64-linux-gnu/include" ] || sudo ln -s /usr/include /usr/aarch64-linux-gnu/include
        [ -d "/usr/aarch64-linux-gnu/lib" ] || sudo ln -s /usr/lib/aarch64-linux-gnu /usr/aarch64-linux-gnu/lib
        
        # 设置编译器路径
        echo "CC=aarch64-linux-gnu-gcc-11" >> $GITHUB_ENV
        echo "CXX=aarch64-linux-gnu-g++-11" >> $GITHUB_ENV
        echo "AR=aarch64-linux-gnu-ar" >> $GITHUB_ENV
        echo "LD=aarch64-linux-gnu-ld" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV

    - name: Test cross compiler
      run: |
        echo 'int main(){return 0;}' > test.c
        aarch64-linux-gnu-gcc-11 test.c -o test
        qemu-aarch64-static ./test
        echo "Compiler test exit code: $?"

    - name: Clone FFmpeg
      run: |
        git clone --depth 1 --branch release/6.1 https://github.com/FFmpeg/FFmpeg.git
        cd FFmpeg

    - name: Configure FFmpeg
      run: |
        cd FFmpeg
        ./configure \
          --prefix="/usr/local" \
          --enable-cross-compile \
          --cross-prefix=aarch64-linux-gnu- \
          --target-os=linux \
          --arch=aarch64 \
          --extra-cflags="-mcpu=cortex-a72 -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -O3" \
          --extra-ldflags="-L/usr/aarch64-linux-gnu/lib" \
          --sysroot=/usr/aarch64-linux-gnu \
          --enable-shared \
          --enable-pic || { cat ffbuild/config.log; exit 1; }

    - name: Build FFmpeg
      run: |
        cd FFmpeg
        make -j$(nproc)

    - name: Package artifacts
      run: |
        cd FFmpeg
        make install DESTDIR=./install
        tar -czvf ../ffmpeg_rpi4b.tar.gz -C ./install .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg_rpi4b_build
        path: ffmpeg_rpi4b.tar.gz
        retention-days: 7
