name: Cross Compile FFmpeg for Raspberry Pi 4B

on:
  push:
    branches:
      - main

jobs:
  cross_compile:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install dependencies for cross-compilation
      - name: Install cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            yasm \
            git \
            wget \
            cmake \
            curl \
            python3 \
            python3-pip \
            qemu-user-static \
            gcc-arm-linux-gnueabihf \
            g++-arm-linux-gnueabihf \
            libfdk-aac-dev \
            libx264-dev \
            libvpx-dev \
            libopus-dev \
            libfreetype6-dev \
            libx265-dev \
            libbcm-host-dev

      # Step 3: Set up the cross-compilation environment
      - name: Set up cross-compilation environment
        run: |
          export CROSS_PREFIX=arm-linux-gnueabihf-
          export SYSROOT=/path/to/raspberrypi/sysroot
          export PATH=$CROSS_PREFIX/bin:$PATH

      # Step 4: Download and configure FFmpeg
      - name: Download and configure FFmpeg
        run: |
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg
          ./configure \
            --prefix=$SYSROOT/usr \
            --arch=arm \
            --target-os=linux \
            --cross-prefix=$CROSS_PREFIX \
            --sysroot=$SYSROOT \
            --enable-cross-compile \
            --enable-gpl \
            --enable-nonfree \
            --enable-libx264 \
            --enable-libvpx \
            --enable-libopus \
            --enable-libfdk-aac \
            --enable-libfreetype \
            --enable-libx265 \
            --enable-bcm_host

      # Step 5: Compile FFmpeg for Raspberry Pi 4B
      - name: Compile FFmpeg
        run: |
          make -j$(nproc)
          make install

      # Step 6: Upload the compiled FFmpeg binary
      - name: Upload FFmpeg binary
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-armv7
          path: ffmpeg/ffmpeg  # Adjust if necessary
