jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install toolchain
      run: |
        sudo dpkg --add-architecture arm64
        sudo apt-get -qq update
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          crossbuild-essential-arm64 \
          qemu-user-static \
          pkg-config \
          libgmp-dev:arm64 \
          libmpfr-dev:arm64 \
          libmpc-dev:arm64 \
          libssl-dev:arm64 \
          nasm

    - name: Setup sysroot
      run: |
        SYSROOT="/usr/aarch64-linux-gnu"
        sudo mkdir -p $SYSROOT
        sudo ln -sf /usr/lib/aarch64-linux-gnu $SYSROOT/lib
        sudo ln -sf /usr/include/aarch64-linux-gnu $SYSROOT/include

    # Remaining steps remain the same but watch for these potential issues:
    # 1. FFmpeg repo URL should be https://github.com/FFmpeg/FFmpeg.git
    # 2. Verify cross-compile flags and sysroot paths during configuration
