name: RaspberryPi Cross-Compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      CC: aarch64-linux-gnu-gcc
      CXX: aarch64-linux-gnu-g++

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: src  # 显式定义代码路径

    - name: Validate files
      run: |
        if [ ! -f "src/CMakeLists.txt" ]; then
          echo "##[error]CMakeLists.txt missing in src/"
          ls -R src/
          exit 1
        fi

    - name: Setup toolchain
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Configure CMake
      run: |
        cmake -B build -S src \
          -DCMAKE_TOOLCHAIN_FILE=src/cmake/aarch64-toolchain.cmake

    - name: Build
      run: cmake --build build -j $(nproc)
