name: Cross-Compile for RPi4B

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      CC: aarch64-linux-gnu-gcc
      CXX: aarch64-linux-gnu-g++

    steps:
    - name: Checkout code (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: recursive  # 确保子模块同步 [5](@ref)

    - name: Setup toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            qemu-user-static

    - name: Configure build
      working-directory: ${{ github.workspace }}  # 明确工作目录 [6](@ref)
      run: |
        cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_VERBOSE_MAKEFILE=ON

    - name: Compile
      run: |
        cmake --build build -j $(nproc)
        # 二进制验证
        file build/rasp-ffmpeg | grep "ARM aarch64"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: raspberry-bin
        path: build/rasp-ffmpeg
        retention-days: 7
