name: Build FFmpeg for Raspberry Pi 4B

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install toolchain
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          build-essential \
          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          libc6-dev-arm64-cross \
          qemu-user-static \
          crossbuild-essential-arm64 \
          pkg-config-aarch64-linux-gnu \
          libgmp-dev:arm64 \
          libmpfr-dev:arm64 \
          libmpc-dev:arm64 \
          libssl-dev:arm64 \
          nasm

    - name: Setup sysroot
      run: |
        sudo mkdir -p /usr/aarch64-linux-gnu
        sudo apt-get install -y libc6-arm64-cross libstdc++6-arm64-cross
        sudo ln -sf /usr/aarch64-linux-gnu/lib /usr/lib/aarch64-linux-gnu
        sudo ln -sf /usr/include /usr/aarch64-linux-gnu/include

    - name: Clone FFmpeg
      run: git clone --depth 1 --branch release/6.1 https://github.com/FFmpeg/FFmpeg.git

    - name: Configure FFmpeg
      run: |
        cd FFmpeg
        export CC="aarch64-linux-gnu-gcc"
        export CXX="aarch64-linux-gnu-g++"
        export PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig"
        export PKG_CONFIG_SYSROOT_DIR="/usr/aarch64-linux-gnu"
        
        ./configure \
          --prefix="/usr/local" \
          --enable-cross-compile \
          --cross-prefix=aarch64-linux-gnu- \
          --target-os=linux \
          --arch=aarch64 \
          --extra-cflags="-mcpu=cortex-a72 -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -O3" \
          --extra-ldflags="-L/usr/aarch64-linux-gnu/lib" \
          --sysroot=/usr/aarch64-linux-gnu \
          --enable-shared \
          --enable-pic \
          --enable-gpl \
          --enable-version3 \
          --enable-nonfree || { cat ffbuild/config.log; exit 1; }

    - name: Build and package
      run: |
        cd FFmpeg
        make -j$(nproc)
        make install DESTDIR=./install
        tar -czvf ../ffmpeg_build.tar.gz -C ./install .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg_rpi4_build
        path: ffmpeg_build.tar.gz
