name: Build FFmpeg with Dependencies

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup environment
      run: |
        sudo apt-get update -y
        sudo apt-get purge -y libvpx* libogg* libtheora* x264 ffmpeg yasm
        sudo apt-get install -y \
          build-essential git python3 python3-pip bzip2 xz-utils \
          libtool automake autoconf flex bison libgtk-3-dev libfreetype-dev \
          libharfbuzz-dev nasm meson ninja-build cmake pkg-config \
          libass-dev libfdk-aac-dev libmp3lame-dev libopus-dev \
          libvorbis-dev libvpx-dev libx264-dev libx265-dev \
          libdav1d-dev libsvtav1-dev libaom-dev libssl-dev \
          libwebp-dev libpng-dev libjpeg-dev

    - name: Build remaining dependencies
      run: |
        # 部分需要从源码编译的组件
        export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
        export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"

        # 编译 harfbuzz（如果系统版本不足）
        HARFBUZZ_VER=8.3.0
        wget https://github.com/harfbuzz/harfbuzz/archive/refs/tags/$HARFBUZZ_VER.tar.gz
        tar xzf $HARFBUZZ_VER.tar.gz
        cd harfbuzz-$HARFBUZZ_VER
        meson setup build --prefix=/usr --buildtype=release
        ninja -C build
        sudo ninja -C build install
        cd ..

        # 其他需要源码编译的依赖项...

    - name: Build FFmpeg
      run: |
        git clone --depth 1 --branch n4.0.2 https://github.com/FFmpeg/FFmpeg.git
        cd FFmpeg

        ./configure \
          --prefix=/usr/local \
          --enable-gpl \
          --enable-version3 \
          --enable-nonfree \
          --enable-shared \
          --disable-static \
          --enable-libass \
          --enable-libfdk-aac \
          --enable-libfreetype \
          --enable-libmp3lame \
          --enable-libopus \
          --enable-libvorbis \
          --enable-libvpx \
          --enable-libx264 \
          --enable-libx265 \
          --enable-openssl

        make -j$(nproc)
        sudo make install
        sudo ldconfig

    - name: Verify build
      run: |
        ffmpeg -version
        ldconfig -p | grep -E 'libx264|libx265|libavcodec'
